### PR TITLE
Update from staged recipe

### LINKED ISSUE #4: Symlinks to shared libraries are mistakenly destroyed
```
$ ls -l $CONDA_PREFIX/lib/libcutensornet*
-rwxrwxr-x 3 leof leof 3257184 Dec 22 11:16 /home/leof/miniforge3/envs/cqun-dev/lib/libcutensornet.so
-rwxrwxr-x 3 leof leof 3257184 Dec 22 11:16 /home/leof/miniforge3/envs/cqun-dev/lib/libcutensornet.so.0
-rwxrwxr-x 3 leof leof 3257184 Dec 22 11:16 /home/leof/miniforge3/envs/cqun-dev/lib/libcutensornet.so.0.1.0.30
$ ls -l $CONDA_PREFIX/lib/libcustatevec*
-rwxrwxr-x 3 leof leof 6013896 Dec 22 11:16 /home/leof/miniforge3/envs/cqun-dev/lib/libcustatevec.so
-rwxrwxr-x 3 leof leof 6013896 Dec 22 11:16 /home/leof/miniforge3/envs/cqun-dev/lib/libcustatevec.so.0
-rwxrwxr-x 3 leof leof 6013896 Dec 22 11:16 /home/leof/miniforge3/envs/cqun-dev/lib/libcustatevec.so.0.1.0.30
```

### PR DESCRIPTION
**Pull request by leofang**
Follow-up of https://github.com/conda-forge/staged-recipes/pull/17550. Close #4.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
Blocked by https://github.com/conda-forge/cutensor-feedstock/pull/26.

**Comment by jakirkham** [comment]
Restarted CI since that had been merged and published packages a while back

**Comment by leofang** [comment]
Reported internally the test failure due to undefined references (CUQNT-546). Let me investigate a workaround.

**Comment by leofang** [comment]
No luck. `__tls_get_addr_opt` is a linker optimization which is not something whose version info can be naively erased. Will disable ppc64le builds for now...

**Comment by jakirkham** [comment]
Maybe [this blogpost]( http://maskray.me/blog/2021-02-14-all-about-thread-local-storage ) is useful?

**Comment by leofang** [comment]
Yes, it looks nice and very through, though my current understanding is the binary needs to be recompiled and some linker flags should be set at the link time to not generate the `__tls_get_addr_opt` symbol. Doesn't seem that patchelf can patch the behavior easily?

**Comment by leofang** [comment]
Let's merge and I'll open an issue later to keep track of ppc64le builds!

**Comment by jakirkham** [comment]
Agreed wasn't suggesting we try to fix that right now. Just digging up info that might be useful in the future :)

**Comment by jakirkham** [comment]
Thanks Leo! 😀

**Pull request merged**
