### PR TITLE
cuquantum v22.11.0

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
cc: @DmitryLyakh for vis

**Comment by leofang** [comment]
@conda-forge/cuquantum @dmitrylyakh anyone wanna take a look?

**Comment by JeremyWangNVDA** [comment]
> 

do we use 11.2? is there anything requiring 11.8 headers?

**Comment by leofang** [comment]
Nothing from Python. On conda-forge, the default CUDA build matrix is [10.2-11.2](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/eba9e7e8120ba06030284e406922a0e1863fd4e2/recipe/conda_build_config.yaml#L54-L59), so we are picking the highest one here. It doesn't really matter as long as it's CUDA 11.

**Review by yangcal — APPROVED** [review]
All contents under `recipe` looks good to me

**Comment by leofang** [comment]
> I wonder why the bot does not send a version-update PR... need to check, don't merge too quickly.

I checked the bot log: https://github.com/regro/autotick-bot/actions/runs/3587636859/jobs/6038203664 it seems the heuristics for guessing the next version needs to be relaxed. 22.07 -> 22.11 is a wide span that the bot failed to guess. No big issue here otherwise.

**Comment by leofang** [comment]
It seems Travis CI still keeps failing (it's known very flaky, which was why I disabled it in the past...) Let's see if #20 would fix it.

**Comment by leofang** [comment]
> > I wonder why the bot does not send a version-update PR... need to check, don't merge too quickly.
> 
> I checked the bot log: https://github.com/regro/autotick-bot/actions/runs/3587636859/jobs/6038203664 it seems the heuristics for guessing the next version needs to be relaxed. 22.07 -> 22.11 is a wide span that the bot failed to guess. No big issue here otherwise.

Proof:
```python
>>> from conda_forge_tick import update_sources
>>> nv = update_sources.NVIDIA()
>>> nv.next_ver_func('cuquantum', '22.03.0')
'22.05.0.41'
>>> nv.next_ver_func('cuquantum', '22.07.0')
'22.07.1.14'
>>> nv.next_ver_func('cuquantum', '22.07.1')  # <- found nothing
>>>
```

**Pull request merged**
